org: pmansell
app: salve
service: server
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'eu-west-2'}

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

package:
  include:
     - data/**

functions:
  getClinics:
    handler: functions/getClinics.handler
    events:
      - http:
          path: clinics
          method: get
          cors: true
  getPatients:
    handler: functions/getPatients.handler
    events:
      - http:
          path: patients/{id}
          method: get
          cors: true
